# Generated by Django 6.0.2 on 2026-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
