# Generated by Django 6.0.2 on 2026-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escn', '0002_alter_accounts_acc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
